<?php
include("connect.php");
$con_person = $_POST['con_person'];
print $con_person;
$com_id = $_POST['com_id'];
print $com_id;
$title = $_POST['title'];
print $title;
$department = $_POST['department'];
print $department;
$city = $_POST['city'];
print $city;
$state = $_POST['state'];
print $state;
$country = $_POST['country'];
print $country;
$edu_level = $_POST['edu_level'];
print $edu_level;
$job_type = $_POST['job_type'];
print $job_type;
$max_salary = $_POST['max_salary'];
print $max_salary;
$min_salary = $_POST['min_salary'];
print $min_salary;
$job_des = $_POST['job_des'];
print $job_des;
$post_date = $_POST['post_date'];
print $post_date;
$q = "insert into job_posting(con_person,com_id,title,department,city,job_type,min_salary,state,country,edu_level,max_salary,job_des,post_date,post_by) values ('$con_person','$com_id','$title','$department','$city','$job_type','$min_salary','$state','$country','$edu_level','$max_salary','$job_des','$post_date','$post_by')";
mysqli_query($cn, $q);
print $q;
header("location:cindex.php");